/// Represents a category with its associated details.
class CategoryModel {
  final String id;
  final String name;
  final String imageUrl;
  final String description;
  final String textContent;

  CategoryModel({
    required this.id,
    required this.name,
    required this.imageUrl,
    required this.description,
    required this.textContent,
  });

  /// Creates a [CategoryModel] from a Firebase Realtime Database snapshot.
  ///
  /// This method extracts the **id** from the `child.key`
  /// and maps the rest of the properties from the snapshot's child data.
  ///
  /// - **Parameters:**
  ///   - `id`: The Firebase key for the category (generated by Firebase, not user-specified).
  ///   - `data`: The map of data from Firebase containing category details.
  ///
  /// - **Returns:** A [CategoryModel] populated with the provided data.
  factory CategoryModel.fromMap(String id, Map<dynamic, dynamic> data) {
    return CategoryModel(
      id: id,
      name: data['name'] ?? '',
      imageUrl: data['image_url'] ?? '',
      description: data['description'] ?? '',
      textContent: data['text_content'] ?? '',
    );
  }
}