// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// **Select Firebase Options for the Current Platform**
  ///
  /// Determines the appropriate Firebase options based on the platform
  /// the app is currently running on (e.g., **Web**, **Android**, **iOS**, **macOS**, **Windows**).
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web-specific Firebase options
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Return Android-specific Firebase options
      case TargetPlatform.iOS:
        return ios; // Return iOS-specific Firebase options
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        // If the platform is not one of the above, throw an error
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHPtDSTfSgDf9KxgUITriKG0JIfS4UvA',
    appId: '1:40007034184:web:8f4041bd2dad9b72eb7f7d',
    messagingSenderId: '40007034184',
    projectId: 'nbahighlights-e3d26',
    authDomain: 'nbahighlights-e3d26.firebaseapp.com',
    databaseURL: 'https://nbahighlights-e3d26-default-rtdb.firebaseio.com',
    storageBucket: 'nbahighlights-e3d26.firebasestorage.app',
    measurementId: 'G-20EXP70V0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmLHxqF15sRPTQ_C3w6mzG2ds4ADjM95c',
    appId: '1:40007034184:android:f36356514f0cac45eb7f7d',
    messagingSenderId: '40007034184',
    projectId: 'nbahighlights-e3d26',
    databaseURL: 'https://nbahighlights-e3d26-default-rtdb.firebaseio.com',
    storageBucket: 'nbahighlights-e3d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwz2OkqGmKKdbOHhelv-z3g8TTsSB2-FY',
    appId: '1:40007034184:ios:a98ec7da8a86fa17eb7f7d',
    messagingSenderId: '40007034184',
    projectId: 'nbahighlights-e3d26',
    databaseURL: 'https://nbahighlights-e3d26-default-rtdb.firebaseio.com',
    storageBucket: 'nbahighlights-e3d26.firebasestorage.app',
    iosBundleId: 'com.example.nbaHighlightsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwz2OkqGmKKdbOHhelv-z3g8TTsSB2-FY',
    appId: '1:40007034184:ios:a98ec7da8a86fa17eb7f7d',
    messagingSenderId: '40007034184',
    projectId: 'nbahighlights-e3d26',
    databaseURL: 'https://nbahighlights-e3d26-default-rtdb.firebaseio.com',
    storageBucket: 'nbahighlights-e3d26.firebasestorage.app',
    iosBundleId: 'com.example.nbaHighlightsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGHPtDSTfSgDf9KxgUITriKG0JIfS4UvA',
    appId: '1:40007034184:web:19133fe51452c98aeb7f7d',
    messagingSenderId: '40007034184',
    projectId: 'nbahighlights-e3d26',
    authDomain: 'nbahighlights-e3d26.firebaseapp.com',
    databaseURL: 'https://nbahighlights-e3d26-default-rtdb.firebaseio.com',
    storageBucket: 'nbahighlights-e3d26.firebasestorage.app',
    measurementId: 'G-6CVFD5Z9HQ',
  );

}